### ISSUE TITLE
[Question] change field feature name

### ISSUE THREAD

**Issue by Ripki-Dev** [trivago/cluecumber#313]
hello, I new using karate and cluecumber. 
i use this report because this report is very cool & have much detail information.
when i run karate test, I got json that have value like this.

<img width="440" alt="Jepretan Layar 2023-08-01 pukul 13 31 46" src="https://github.com/trivago/cluecumber/assets/92913498/25ae4473-9135-4b73-9eb8-1e9d79256adf">

in cluecumber table report will show like this (i think this data is parse from relativePath in json file), CMIIW

<img width="329" alt="Jepretan Layar 2023-08-01 pukul 13 32 28" src="https://github.com/trivago/cluecumber/assets/92913498/2d8b9cf5-e13a-461a-8f6a-53f1e542044b">

my question is, can i change from relativePath to name for fill the data tables report?

**Comment by bischoffdev** [comment]
Thank you for this, I will look at a way to do this.

**Comment by bischoffdev** [comment]
I checked this. This information is not contained in the Cucumber JSON file (there the feature name is set as the feature file name) but in an additional file called `karate-summary-json`. Since Cluecumber only uses the Cucumber JSON format, this would be an additional step that is Karate exclusive.
To have the feature name here, the way that Karate writes these JSON files has to be modified so that the feature name is written there. So this is an issue that should rather be reported in the Karate repo.
