### ISSUE TITLE
Unable to generate cluecumber reports on test failures and unable to download reports

### ISSUE THREAD

**Issue by SayyedaNousheen** [trivago/cluecumber#341]
Problem

1. We need to generate reports irrespective of the build status with accurate pass / fail results (how can we achieve this, an example code snippet will be helpful)
2. Unable to download the html reports to share it with team
3. Also need to know how it can be integrated with Jenkins and sent as an attachment in email
4. Can I keep customParameters dynamic? Instead of passing static value

Expected Solution:
1. Provision or workaround to generate cluecumber irrespective of build or test status
2. Ability to download index.html reports to share it with team 
3. Provision to integrate index.html reports with Jenkins and share it through email
4. Should be able to pass dynamic customParameters

Cluecumber reporting is very detailed and impressive, it would be great if there is some workaround to achieve above scenarios.

**Comment by bischoffdev** [comment]
Hello, thanks for the questions.

1. This has been adressed multiple times here already. This is independent of Cluecumber, but a property of the standard Maven flow. Your Maven project must either be set up so that reporting is also executed when failures occur. Alternatively, the Maven goal can also be called separately after the test run (e.g. via shell script, Makefile or CICD pipeline implementation).  You can also use the Cluecumber core variant to generate the report via code.
2. This is not enough information. The report is just a set of HTML files, CSS and JS so this can be packed and shared already (e.g. in a zip). If you store the reports in a cloud bucket or ftp location that is accessible via the web, sharing the link would be enough.
3. The Jenkins integration highly depends on your setup. It can be integrated in your Maven flow, triggered as a separate Maven call in Groovy, Bash, Make or any other technologies you use. There is no dedicated Jenkins plugin available.
4. Custom parameters can be dynamic by defining properties in the `pom.xml` file and using those in place of the static values. These properties can be overridden from the outside or dynamically set within the POM file, e.g. with the Antrun plugin.
