### ISSUE TITLE
Support for new cucumber message format (ndjson)

### ISSUE THREAD

**Issue by nayanab123** [trivago/cluecumber#351]
Cucumber has introduced message formatter which generates an ndjson as an alternative to JSON formatters.
The cucumber contributor team has been strongly recommending the use of the new format instead of JSON.
Are there any plans to update this tool to support ndjson as well?

**Comment by bischoffdev** [comment]
Hello @nayanab123 , do you have a source for this recommendation? ndjson is typically associated with the Cucumber message protocol feature. I know there used to be some discussion around that but in the end, it was decided to also keep the JSON output at the end of a test run since too many external tools depend on it.

**Comment by bischoffdev** [comment]
Closed as there was no reaction.
